### PR TITLE
Fix checks

### LINKED ISSUE #500: @jdhoffa yes, sounds good to me. Will you make an issue for it?
These seem to be a result of changes in `r2dii.analysis` and `testthat`.

See here for more context:

_Originally posted by @MonikaFu in https://github.com/RMI-PACTA/r2dii.plot/issues/499#issuecomment-1342498583_

### LINKED ISSUE #507: Review and handle failing tests
This package could benefit from some overall maintenance. There are several failing and warning tests (some are likely quite easy to fix).

### PR DESCRIPTION
**Pull request by MonikaFu**
Closes #500 
Closes #507 

Update code so checks are passing.

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -38,7 +38,7 @@ abort_if_has_zero_rows <- function(data, env) {
 }
 
 hint_if_missing_names <- function(expr, like) {
-  rlang::with_handlers(
+  withCallingHandlers(
```
Comment (jdhoffa) [inline R/utils.R:41]: N.B. Why do we need calling handlers actually?

**Review by jdhoffa — APPROVED** [review]
yay LGTM

File: R/utils.R (hunk 1 above)
Comment (MonikaFu) [reply R/utils.R:41]: I believe that the handlers are there so that we can give a more informative error message. I wasn't the one who wrote this function, though, so not 100% sure. Maybe at some point we should evaluate if the error handling complexity provides adequate benefits in this case?

Comment (jdhoffa) [reply R/utils.R:41]: Yup maybe just good to make a new issue about it, but it could think about assessing if it's worth it

Comment (cjyetman) [reply R/utils.R:41]: made a new issue for it #509
